# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [2]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(200, 50))
A

array([[59, 61, 31, ..., 43, 14, 83],
       [ 8, 79, 59, ..., 33, 38, 78],
       [98, 89, 96, ..., 10, 17, 52],
       ...,
       [26, 93, 53, ..., 75, 83, 79],
       [64, 62, 98, ..., 50, 10, 39],
       [70, 48, 64, ..., 38, 45, 61]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [4]:
B = np.transpose(np.random.permutation(np.transpose(A)))
B

array([[68, 51, 61, ...,  1, 42, 90],
       [51, 73, 79, ..., 41, 49, 52],
       [60, 37, 89, ..., 66, 21, 21],
       ...,
       [44, 78, 93, ...,  6, 38, 73],
       [72, 28, 62, ..., 16,  9, 73],
       [ 0,  9, 48, ..., 12, 23, 17]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [6]:
C = A[A[:,::2].sum(axis=1) > A[:,1::2].mean()]
C

array([[59, 61, 31, ..., 43, 14, 83],
       [ 8, 79, 59, ..., 33, 38, 78],
       [98, 89, 96, ..., 10, 17, 52],
       ...,
       [26, 93, 53, ..., 75, 83, 79],
       [64, 62, 98, ..., 50, 10, 39],
       [70, 48, 64, ..., 38, 45, 61]])

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [3]:
i = np.argmax(np.max(A, axis=1) - np.min(A, axis=1))
i

0

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [10]:
D = np.argsort(A.reshape(1, len(A)*len(A[0]))).reshape(len(A),len(A[0])) + 1
D

array([[1297, 4351, 7249, ..., 8990, 7070, 6330],
       [9022, 5318, 1895, ..., 8826, 9967, 7806],
       [7395, 2650, 7883, ..., 9552, 2186, 5079],
       ...,
       [1590, 9463, 5905, ..., 8459, 9154, 8436],
       [1765, 8676, 9551, ..., 9409, 3679, 5565],
       [8647, 2069, 2574, ..., 1857, 7996, 6954]])

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массив, в каждой строке которого максимальный элемент равен $1$, минимальный - $0$. 

In [26]:
E = (A - A.min(axis=1)[:1]) / (A.max(axis=1)[:1] - A.min(axis=1)[:1])
E

array([[0.5959596 , 0.61616162, 0.31313131, ..., 0.43434343, 0.14141414,
        0.83838384],
       [0.08080808, 0.7979798 , 0.5959596 , ..., 0.33333333, 0.38383838,
        0.78787879],
       [0.98989899, 0.8989899 , 0.96969697, ..., 0.1010101 , 0.17171717,
        0.52525253],
       ...,
       [0.26262626, 0.93939394, 0.53535354, ..., 0.75757576, 0.83838384,
        0.7979798 ],
       [0.64646465, 0.62626263, 0.98989899, ..., 0.50505051, 0.1010101 ,
        0.39393939],
       [0.70707071, 0.48484848, 0.64646465, ..., 0.38383838, 0.45454545,
        0.61616162]])

# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [27]:
a1 = A[:,1::2]
a1
a2 = A[:,0::2]
F = np.concatenate((a2, a1), axis=1)
F

array([[59, 31,  3, ..., 39, 43, 83],
       [ 8, 59, 25, ..., 71, 33, 78],
       [98, 96, 32, ..., 71, 10, 52],
       ...,
       [26, 53, 76, ..., 55, 75, 79],
       [64, 98,  9, ..., 61, 50, 39],
       [70, 64, 55, ..., 80, 38, 61]])

# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

In [33]:
len(A[np.all(A > 5, axis=1)])

9

# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [32]:
np.mean(np.split(A, 10), axis=0)

array([[37.3, 60.8, 45. , 39.8, 33.5, 51.9, 54.1, 38.7, 42.5, 39.5, 43.1,
        51.9, 56. , 58.7, 53.2, 48.8, 49.7, 42.1, 51.8, 63.6, 52.1, 49.2,
        39. , 68.7, 64.2, 42.6, 61.8, 62.6, 37.8, 56.5, 42.8, 53.5, 46.8,
        48.5, 42. , 36.9, 38.1, 56. , 32.1, 44.6, 44.9, 54.9, 38.9, 57. ,
        66.2, 44.7, 50.3, 42.6, 42.6, 54.9],
       [43.3, 55.4, 44.4, 57.2, 47.5, 46.2, 46. , 75. , 53.7, 32. , 48.2,
        59. , 56.2, 53.2, 63.8, 67.4, 62.4, 25.3, 70.5, 42.4, 42.1, 48. ,
        33.8, 58.9, 48.1, 58.6, 36.9, 44.9, 52.9, 39.1, 51.8, 45.3, 40.1,
        43.5, 49.3, 55.2, 54.9, 51.7, 57.6, 55.4, 53.9, 57.2, 59.4, 58.4,
        47.1, 48.9, 46.8, 31.7, 50.2, 56.7],
       [65.4, 45.8, 44.4, 49. , 36. , 61.7, 40.8, 50.7, 68.2, 56. , 47.1,
        29.5, 52.4, 41.2, 53.6, 40.5, 63.4, 61.3, 51.2, 55.8, 56.1, 46. ,
        47. , 40.5, 49.4, 42.1, 61.4, 38.9, 45.8, 49.2, 46.2, 32.7, 57.2,
        46.1, 66.2, 47.5, 57.1, 40.8, 42.2, 43.8, 56.1, 62.1, 52.3, 42.8,
        52.1, 52.4, 37

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A`

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [2]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

[0, 4, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [3]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

2003

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 

# Задание 2.17 (5 баллов)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [4]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


-0.13580565475012618

Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+5 баллов)
- [Taichi](https://github.com/taichi-dev/taichi) (+5 баллов)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+2 балла)

Сравните производительность.