# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [52]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(200, 50))
A

array([[79, 65, 10, ..., 71, 53, 99],
       [74, 50,  0, ..., 16,  8, 19],
       [95,  3,  9, ..., 70, 30, 51],
       ...,
       [27, 35, 95, ..., 41, 48, 85],
       [85, 12, 81, ..., 17, 95, 10],
       [ 3, 76, 10, ..., 82,  9, 20]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [53]:
B = np.transpose(np.random.permutation(np.transpose(A)))
B

array([[ 0, 28, 10, ..., 29, 57, 14],
       [41, 44,  0, ..., 62, 29, 59],
       [31, 21,  9, ..., 42, 96, 78],
       ...,
       [53, 68, 95, ..., 37, 62, 10],
       [18, 76, 81, ...,  0, 94, 72],
       [47, 63, 10, ..., 23, 86, 13]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [54]:
C = A[A[:,::2].sum(axis=1) > A[:,1::2].mean()]
C

array([[79, 65, 10, ..., 71, 53, 99],
       [74, 50,  0, ..., 16,  8, 19],
       [95,  3,  9, ..., 70, 30, 51],
       ...,
       [27, 35, 95, ..., 41, 48, 85],
       [85, 12, 81, ..., 17, 95, 10],
       [ 3, 76, 10, ..., 82,  9, 20]])

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [55]:
i = np.argmax(np.max(A, axis=1) - np.min(A, axis=1))
i

0

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [56]:
D = np.argsort(A.reshape(1, len(A)*len(A[0]))).reshape(len(A),len(A[0])) + 1
D

array([[5565,  770,  986, ..., 9907, 2638,  662],
       [6973, 4474, 1887, ..., 2133, 1092, 2490],
       [1489, 2659, 2640, ..., 5929, 9790, 5298],
       ...,
       [7108, 4809, 1196, ..., 4659, 5538, 4491],
       [4654, 1937, 5869, ..., 4630, 6245, 6243],
       [6733,  336, 4935, ..., 3442, 9886, 3663]])

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массив, в каждой строке которого максимальный элемент равен $1$, минимальный - $0$. 

In [57]:
E = (A - A.min(axis=1)[:1]) / (A.max(axis=1)[:1] - A.min(axis=1)[:1])
E

array([[0.7979798 , 0.65656566, 0.1010101 , ..., 0.71717172, 0.53535354,
        1.        ],
       [0.74747475, 0.50505051, 0.        , ..., 0.16161616, 0.08080808,
        0.19191919],
       [0.95959596, 0.03030303, 0.09090909, ..., 0.70707071, 0.3030303 ,
        0.51515152],
       ...,
       [0.27272727, 0.35353535, 0.95959596, ..., 0.41414141, 0.48484848,
        0.85858586],
       [0.85858586, 0.12121212, 0.81818182, ..., 0.17171717, 0.95959596,
        0.1010101 ],
       [0.03030303, 0.76767677, 0.1010101 , ..., 0.82828283, 0.09090909,
        0.2020202 ]])

# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

In [58]:
c = np.arange(1, 11).reshape((-1, 1, 1))   # shape: (10, 1, 1)
A * c   # shape: (200, 50) * (10, 1, 1) = (1, 200, 50) * (10, 1, 1) = (10, 200, 50)

array([[[ 79,  65,  10, ...,  71,  53,  99],
        [ 74,  50,   0, ...,  16,   8,  19],
        [ 95,   3,   9, ...,  70,  30,  51],
        ...,
        [ 27,  35,  95, ...,  41,  48,  85],
        [ 85,  12,  81, ...,  17,  95,  10],
        [  3,  76,  10, ...,  82,   9,  20]],

       [[158, 130,  20, ..., 142, 106, 198],
        [148, 100,   0, ...,  32,  16,  38],
        [190,   6,  18, ..., 140,  60, 102],
        ...,
        [ 54,  70, 190, ...,  82,  96, 170],
        [170,  24, 162, ...,  34, 190,  20],
        [  6, 152,  20, ..., 164,  18,  40]],

       [[237, 195,  30, ..., 213, 159, 297],
        [222, 150,   0, ...,  48,  24,  57],
        [285,   9,  27, ..., 210,  90, 153],
        ...,
        [ 81, 105, 285, ..., 123, 144, 255],
        [255,  36, 243, ...,  51, 285,  30],
        [  9, 228,  30, ..., 246,  27,  60]],

       ...,

       [[632, 520,  80, ..., 568, 424, 792],
        [592, 400,   0, ..., 128,  64, 152],
        [760,  24,  72, ..., 560, 240, 408

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [59]:
a1 = A[:,1::2]
a1
a2 = A[:,0::2]
F = np.concatenate((a2, a1), axis=1)
F

array([[79, 10, 20, ..., 95, 71, 99],
       [74,  0, 28, ..., 59, 16, 19],
       [95,  9, 42, ..., 74, 70, 51],
       ...,
       [27, 95,  9, ..., 32, 41, 85],
       [85, 81, 90, ..., 16, 17, 10],
       [ 3, 10,  1, ..., 59, 82, 20]])

# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

In [60]:
len(A[np.all(A > 5, axis=1)])

11

# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [61]:
np.mean(np.split(A, 10), axis=0)

array([[65.4, 58.5, 46.7, 50.7, 46.6, 54.7, 43.1, 61. , 58.1, 36.1, 50.3,
        50.7, 30.7, 57.2, 41.2, 52. , 63.3, 57. , 63.6, 50.3, 48.2, 39.8,
        54.8, 59.4, 38.9, 41.6, 56.3, 35.1, 47.6, 37.5, 36.6, 31.8, 72.5,
        33.4, 50. , 37.7, 40.8, 59.7, 35.4, 47.8, 50.6, 32.5, 44.8, 47.9,
        61.9, 72.1, 52.8, 51.3, 47.7, 50.5],
       [53.9, 46. , 40.5, 43.6, 40.1, 59.2, 49.1, 52.9, 41.6, 39.8, 57. ,
        58.7, 29.7, 73.4, 42.3, 47.6, 52.5, 49.1, 40.2, 48.1, 52.9, 50.2,
        42.5, 50.5, 54.8, 60.8, 46. , 35.6, 44.5, 48.3, 60.6, 60.1, 54.6,
        44.7, 54.1, 41.9, 74.9, 36.6, 46.9, 50.9, 42.7, 66.5, 65. , 62.8,
        46.4, 42.9, 69.3, 55.3, 48.6, 58. ],
       [45.7, 45.9, 37.7, 57.8, 35.7, 58.1, 44.7, 54.7, 58.2, 45.8, 51.6,
        44.3, 48.7, 52.7, 61.9, 51.6, 31.7, 57.5, 41.8, 35.2, 44.8, 56.4,
        46.7, 49.9, 56.1, 56.7, 56.7, 45.2, 55.7, 46.2, 52.8, 44.4, 49.3,
        42.3, 40.5, 55. , 50.6, 56.7, 31.4, 50.4, 56.2, 60.7, 56.9, 45.8,
        49.5, 48.1, 53

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

In [62]:
_, ind = np.unique(A, return_index=True)
J = A.reshape((1, len(A) * len(A[0])))
J[0][np.sort(ind)]  

array([79, 65, 10, 50, 20, 68, 29, 70, 19,  0, 23, 75, 24, 25, 37, 54, 15,
       18, 17,  5, 76, 14, 84, 94,  7, 57, 38, 97, 72, 21, 53, 22, 48, 28,
       66, 62, 95, 49, 71, 99, 74, 91, 60, 51, 41, 44,  9, 40, 59, 93, 56,
       30, 26, 16, 86,  3, 80, 12, 82,  8, 81, 42, 31, 77,  6, 34, 83, 11,
       78, 63, 58,  1, 87, 96, 85, 32, 35, 36, 61, 13, 46, 64, 98, 39, 52,
       27, 90, 88, 67, 69,  4, 89, 92, 45,  2, 73, 55, 47, 43, 33])

# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A`

In [63]:
np.linalg.norm(A - np.mean(A, axis=0), axis=1)

array([204.70065718, 195.57082873, 208.55588951, 205.83293966,
       229.68306217, 217.38569192, 212.43565861, 216.80975312,
       194.16387164, 205.03231221, 205.08380982, 198.1720693 ,
       184.83175877, 215.59336504, 208.10535565, 214.986509  ,
       203.39112333, 210.41907958, 218.02359746, 189.61782366,
       215.57513551, 200.55275877, 200.3135768 , 187.73691446,
       202.40306087, 203.84415383, 199.53187477, 189.92329781,
       199.92898502, 208.49599289, 212.72883925, 195.38774028,
       175.56670826, 203.2326968 , 202.03878105, 170.33314137,
       199.514358  , 207.59154378, 201.31293811, 212.34711924,
       219.97506461, 216.68603797, 217.66446437, 219.08148952,
       193.91234888, 192.38778301, 186.25272897, 216.05772157,
       203.63111022, 203.81709705, 170.13012388, 205.70619594,
       208.79070633, 200.79088388, 198.97728275, 189.870585  ,
       195.98879828, 186.5711903 , 195.12992864, 207.04929135,
       201.08042931, 205.94166419, 182.19085885, 210.92

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [64]:
np.where(A < 50, 2 * A, 3 * A)

array([[237, 195,  20, ..., 213, 159, 297],
       [222, 150,   0, ...,  32,  16,  38],
       [285,   6,  18, ..., 210,  60, 153],
       ...,
       [ 54,  70, 285, ...,  82,  96, 255],
       [255,  24, 243, ...,  34, 285,  20],
       [  6, 228,  20, ..., 246,  18,  40]])

# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

In [65]:
def moving_average(arr, window_size):
    return np.convolve(arr[0], np.ones(window_size) / window_size, mode='valid') 
    
V = A.reshape((1, len(A) * len(A[0])))
# print(V)
# print(A)
V3 = moving_average(V, 3)
V5 = moving_average(V, 5)
V10 = moving_average(V, 10)

V5 = np.concatenate((V5,  np.zeros(V3.shape[0] - V5.shape[0])))
V10 = np.concatenate((V10,  np.zeros(V3.shape[0] - V10.shape[0])))
V3 + V5 + V10

array([137.13333333, 119.66666667,  98.46666667, ..., 114.06666667,
        51.        ,  37.        ])

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [66]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

[0, 0, 0, 1, 4]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [67]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

1614

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 

# Задание 2.17 (5 баллов)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [68]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


0.97736179787612

Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+5 баллов)
- [Taichi](https://github.com/taichi-dev/taichi) (+5 баллов)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+2 балла)

Сравните производительность.